# <p>Any arbitrary <span style="color: red;">*square*</span> matrix may be decomposed into a symmetric and antisymmetric pair. S and A</p>

Let's consider

$$
M = \begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9
\end{pmatrix}
$$

This formula takes a sum and a difference or M and its transpose, then it will hold true for:
$$
M = \frac{1}{2}(M+M^T) + \frac{1}{2}(M-M^T)
$$

$$
M = S + A
$$

## Let's try this

In [1]:
import numpy as np

In [5]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Transpose M. This means we swap columns for rows and rows for columns.

In [7]:
Mt = M.T
print(Mt)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Let's work through the formula.
$$
S = \frac{1}{2}(M+M^T)
$$

In [15]:
S = 1/2 * (M + Mt)
print(S)

[[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]


And now the other part of the formula
$$
A = \frac{1}{2}(M-M^T)
$$

In [16]:
A = 1/2 * (M - Mt)
print(A)

[[ 0. -1. -2.]
 [ 1.  0. -1.]
 [ 2.  1.  0.]]


So...is this antisymmetric? It looks like it because all diagonal is zero, and the upper triangle is the negative of the lower triangle.
A test function for this follows:

In [17]:
def is_antisymmetric(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        return False  # Not a square matrix
    return np.allclose(matrix, -matrix.T)

is_antisymmetric(A)

True

### Let's add A to B to show that this really does equal M

In [12]:
print(A + B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [13]:
(A + B ) == M

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Why is this important and useful?
* You can split a complex problem into two smaller problems and work on each A and B separately.
* You know or will learn about eigenvectors and eigenvalues. It's a fact that *symmetric* matrices have special properties.
    * Symmetric matrices have real eigenvalues.
    * Symmetric matrices have orthogonal eigenvectors
* In this context *real* means ordinary decimal numbers like 2.1 or -99
    * This is in contrast to other kinds of numbers like complex numbers which have two components. A real number is scalar...meaning it grows or shrinks a *thing* without changing the overall internal relationship of the thing.
* *orthogonal* means "at right angles to". However the concept extends from two dimentions into three and beyond. Although you can't visualise orthogonal axes in 5 dimensions, *orthogonality* in a five-dimensional space is a useful mathmematical construct.

In fluid dynamics the stress tensor is symmetric and represents physical forces, and antisymmetric components can represent rotational components of motion.

## For machine learning

Symmetric matrices often arise in the form of covariance matrices, which are used for understanding the relationship between variables. Decomposing matrices in this context can help in principal component analysis (PCA) and other techniques for dimensionality reduction.

## Optimisation problems

Some algorithms are more efficient when applied to symmetric matrices, due to their reduced computational complexity.